### ISSUE TITLE
Setup continuous deployment

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#1]
Setup continuous deployment so that pushes to `master` are deployed to https://thenewboston.network

TODO:
- [DONE] Publish docker image to github registry
- [DONE] Shell script to deploy Core manually
- [DONE] Provision an EC2 instance
- [DONE] Github actions to use that script and deploy to https://thenewboston.network

Relates to:
- [DONE] [Dockerize Project](https://github.com/thenewboston-developers/Core/issues/2)
- [Configure thenewboston.network domain with HTTPS](https://github.com/thenewboston-developers/Core/issues/5)

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/51

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/52

**Comment by dmugtasimov** [comment]
@buckyroberts manually deployed to http://52.32.121.197/ . We continue to work to setup automatic deployment

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/53

**Comment by dmugtasimov** [comment]
@buckyroberts also available with `ssh ubuntu@thenewboston.network -i core-keypair.pem` and http://thenewboston.network/

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/54

**Comment by dmugtasimov** [comment]
@buckyroberts autodeploys from master now. TLS will be configured in https://github.com/thenewboston-developers/Core/issues/5
