### ISSUE TITLE
Create superuser for live environment

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#10]
Share credentials with Bucky.

**Comment by dmugtasimov** [comment]
user and password in discord DM

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/53

**Comment by dmugtasimov** [comment]
@buckyroberts fixed here: https://github.com/thenewboston-developers/Core/pull/68

The issue appeared because of a new security measure introduced in Django 4 when HTTPS is enabled
