### ISSUE TITLE
FieldTracker

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#114]
We may be able to remove this now that display name and avatar have been removed https://github.com/thenewboston-developers/Core/blob/master/core/accounts/models/account.py#L20

**Comment by dmugtasimov** [comment]
@buckyroberts added this comment: https://github.com/thenewboston-developers/Core/pull/117

Please, let me know if you still want to remove it

**Comment by buckyroberts** [comment]
@dmugtasimov ok that's fine, we can leave it in.
