### ISSUE TITLE
Core connections

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#116]
Requirements outlined in the [core connections](https://docs.google.com/document/d/1SYg0ny4KYDpyDouDvW9ALXauf-mvLGZQzUqDPk0HhMU/edit?usp=sharing) document.

TODO
====
- [DONE] accounts may only connect to their own WebSocket: will authenticate via signature (use block structure so signed message can’t be reused)
- [CANCELED] PUT /api/peers/{account_number}/ end-point with Authorization HTTP-header base authentication (reuse WebSocket authentication)
- [CANCELED] Restrict block sending
- [CANCELED] DELETE /api/peers/{account_number}/
- [CANCELED] LIST /api/peers/ - with `is_connected` attribute
- [CANCELED] Notifications when logical connection is established
- [CANCELED] Refactor /api/config/self/ to authenticate with Authorization HTTP-header instead of extra attributes in request body
- [DONE] Implement RPC-based online status tracking
- [DONE] Unittest
- [DONE] Update description

Questions
------------
- Are we able to use one model?
- What about for services/accounts allowing all traffic?
- What happens to the logical connections when an account changes from allowing specific logical connections to allowing all traffic?

Discuss naming
------------
- naming may be confusing since we say a LogicConnection is when both parties are connected while below is more of a partial connection

LogicalConnection
- owner_account_number
- counterparty_account_number
- connection_status  # open or closed

**Comment by dmugtasimov** [comment]
@buckyroberts Authentication and authorization are implemented here: https://github.com/thenewboston-developers/Core/pull/118

WebSocket connection must be made with `Authorization` HTTP-header with value formatted as `SToken {account_number}${iso_formatted_datetime}${signature}`

{signature} is produced by signing {iso_formatted_datetime}.
Signing algo can be found here: https://github.com/thenewboston-developers/Core/blob/master/core/accounts/tests/test_channels.py#L12

Example curl to make WebSocket connection:
```
curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: 127.0.0.1:8000" \
     --header "Origin: http://127.0.0.1:8000" \
     --header "Sec-WebSocket-Version: 13" \
     --header "Sec-WebSocket-Key: blbW0wWKLgWgeYOt8UWvag==" \
     --header "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits" \
     --header 'Authorization: SToken eb01f474a637e402b44407f3c1044a0c4b59261515d50be9abd4ee34fcb9075b$2022-07-31T18:01:44.346807+00:00$526b0119f400856627b7c1ac45f205fe7e999bda9576d78bb888a2cb6f06e3985639f1b8f2fc6248a09765fc6c9c60b069cce450a7df0997ed201464cb54b905' \
     -vv \
     "http://127.0.0.1:8000/ws/accounts/eb01f474a637e402b44407f3c1044a0c4b59261515d50be9abd4ee34fcb9075b"
```

**Comment by dmugtasimov** [comment]
WIP branch: https://github.com/thenewboston-developers/Core/tree/feature/api-peers-end-point

**Comment by dmugtasimov** [comment]
WIP branch: https://github.com/thenewboston-developers/Core/tree/feature/peers-over-rpc

**Comment by dmugtasimov** [comment]
@buckyroberts implemented here: https://github.com/thenewboston-developers/Core/pull/126

**Comment by dmugtasimov** [comment]
@buckyroberts 

Some notes:
1. I decided not to persist online status in the database to avoid inconsistencies with actual connection status which may be become not in sync in some cases. For example, if the server crashes the database would still store online statuses that are no longer valid
2. I decided not to store list of peers in the database to make it simpler and also allow multiple connections of the same account have their own set of peers. This will also avoid race condition issues in of multiple connections for the same account.
3. Implementation based on channel layers also allows multiple connections on peer side. It is considered online as long as at least one connection exists.
4. I did not do manual integration testing I may do it next week, unless you do i yourself by that time (please, let me know)
5. I might need to do some clean up and brush up next week (implement low priority tests and make tests DRYer)
