### ISSUE TITLE
Configure thenewboston.network domain with HTTPS

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#5]
I registered the domain **thenewboston.network** on Route 53 however have not done anything else with it yet. We will use that domain for this project.

Once we have a live environment set up, please configure it to point to **thenewboston.network**.

Relates to:
- [DONE] [Setup CI/CD](https://github.com/thenewboston-developers/Core/issues/1)
- [DONE] [Dockerize Project](https://github.com/thenewboston-developers/Core/issues/2)

TODO:
- [CANCELED] Use Debian based nginx image
- [CANCELED] Add snap installation script
- [DONE] Add certbot installation script
- [DONE] Add cerbot setup script
- [DONE] Add auto renewal configuration

**Comment by dmugtasimov** [comment]
We need HTTPS, because we want to login to Django Admin. Otherwise it would not be necessary.

Available at http://thenewboston.network/

TLS will be configured later

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/55
https://github.com/thenewboston-developers/Core/pull/56

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/57

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/59

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/60

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/61

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/62

**Comment by dmugtasimov** [comment]
@buckyroberts HTTPS is configured. I updated README.rst with new URLs and examples:

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/64

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/65
