### ISSUE TITLE
Transaction fee

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#67]
Regarding https://github.com/thenewboston-developers/Core/issues/11#issuecomment-1111074022 we can require a minimum fee to send each message. This is configurable by the node maintainer. It will be similar to these alpha network fields.

<img width="717" alt="Screen Shot 2022-04-29 at 12 16 00 PM" src="https://user-images.githubusercontent.com/8547538/165983765-e6ee7ae0-66ac-45d8-a640-736ba66c0da7.png">

Instead of `account_number` we can have `owner` to represent the node maintainer. We can replace `default_transaction_fee` with `transaction_fee` and set the default (and minimum value) to `1`.

So the `amount` still represents the amount being sent to the `recipient` - this can still be `0`. There will however be an additional fee to send each message which is configurable by the node owner. The minimum fee is `1`. This way the owner can raise the fee to throttle traffic if needed. A `transaction_fee` field can be included in the request body so that the backend can ensure the user is agreeing to the fee (incase it's recently been change). We do not need to include any `owner` or `transaction_fee_account` or anything though. All transaction fees can just be be deducted from the senders account (basically burnt).

**Sample request body:**
```json
{
  "sender": "eb01f474a637e402b44407f3c1044a0c4b59261515d50be9abd4ee34fcb9075b",
  "recipient": "6fac7f7e2b90173bfc6ef8ee34f9c92438b5eb8f579ef8d84464b820bbfecfc1",
  "amount": 0,
  "transaction_fee": 1,
  "payload": {
    "message": "Hey"
  },
  "signature": "df64c0689b2f203c345269aea47d90576c6c37ce168d6084016772f79b2dfb1228de053ec753a2b87e4b404929a8bc6123acf56e7acd178716077e4ddb9b3208"
}
```

TODO:
- [DONE] Choose a third-party Django battery to implement general configuration
- [DONE] Implement updateable settings:
    - [DONE] Model
    - [DONE] Configuration (setting name, default value, description)
    - [DONE] Programmatic read / write functions
    - [DONE] Make settings available in Django Admin
    - [DONE] Add validation that works on both Django Admin and API level
- [DONE] Implement an API call to change configuration
- [DONE] Implement API call signature verification
- [DONE] Validate that only owner can update their account
- [DONE] Substract transaction_fee from sender account
- [DONE] Validate transaction_fee

**Comment by dmugtasimov** [comment]
I think `transaction_default_fee` is a correct name rather than `default_transaction_fee` (since it ambiguous to mean some sort of default transaction that has a fee).

@buckyroberts do you want `owner` and `transaction_default_fee` be configured via Django Admin or settings.py (env vars) is good enough?

Also why not to name the setting just `transaction_fee` since there is no such thing as non-default transaction fee and also we still force clients to include `transaction_fee` into block body?

**Comment by dmugtasimov** [comment]
```
Bucky — Today at 9:10 PM
Can we keep is as is? So there will be a super user with access to Django admin but that's more just for development. The owner should never need to go into Django admin. The owner as of now is really just the account that can update the transaction_fee via API request.
Or more simply, the owner is the one who can make PATCH requests to /config to change either the owner or transaction_fee
Then GET /config can be public so that the clients can know what the transaction_fee is. We can include the owner in the response just for completeness but it won't really be used for anything.
dmugtasimov — Today at 9:13 PM
How should owner acquire an API token for an API request? Or we do signature-based authentication?
Bucky — Today at 9:13 PM
They can just send in a signed request. We can match the account_number with the owner.
dmugtasimov — Today at 9:14 PM
ok
```

**Comment by dmugtasimov** [comment]
The most promising was https://github.com/jazzband/django-constance . But although there is activity in github on PyPI it was update like 1.5 years ago. Therefore I decide to implement own updateable setting. It should be simple to do.

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/69

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/70

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/71

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/72
