### ISSUE TITLE
DRY up signature validation

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#73]
Moving this TODO to an action item: https://github.com/thenewboston-developers/Core/blob/master/core/settings/serializers.py#L34

```
# TODO(dmu) MEDIUM: Consider DRYing up with core.accounts.serializers.account.AccountSerializer.validate()
#                   Or implementation of Authorization HTTP-header based signing
```

**Comment by buckyroberts** [comment]
From meeting - we will DRY up the existing serializer code.

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/91

**Comment by dmugtasimov** [comment]
@buckyroberts after reviewing the code I figured out that the DRYing does not make sense (it is DRY enough until the point where it would hurt something else)

https://github.com/thenewboston-developers/Core/pull/92
