### ISSUE TITLE
Config.owner logic

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#74]
Any issues with converting `Config.owner` to be a required field?

https://github.com/thenewboston-developers/Core/blob/master/core/settings/models.py#L16

There is an issue when sending a block if there is no `Config.owner` yet. This bit of code was returning `None` and then creating an `Account` with an empty account number and then throwing a 500 when I made the same request again.

https://github.com/thenewboston-developers/Core/blob/master/core/blocks/serializers/block.py#L42

---

<img width="602" alt="Screen Shot 2022-05-03 at 12 22 57 PM" src="https://user-images.githubusercontent.com/8547538/166494698-5b9d2a66-aeb0-42b0-8f26-6e385b13ec89.png">

---

<img width="1247" alt="Screen Shot 2022-05-03 at 12 23 15 PM" src="https://user-images.githubusercontent.com/8547538/166494701-4a50f4f5-c8d7-4e9a-ba28-c0a3840cab9a.png">

**Comment by buckyroberts** [comment]
Thinking about this some more, we do not need to do anything with the owners account when sending blocks. The transaction fee will not be transferred to their account. It will just be deducted from the senders account.

**Comment by buckyroberts** [comment]
From meeting - we will just remove the `owner` account logic from the `BlockSerializer`.

**Comment by dmugtasimov** [comment]
@buckyroberts btw, it looks like Django inconsistency when provided None for a private key. Instead of raising an error it coerces it to an empty string (`''`) and creates such an account:

```
(Pdb) fee_account, is_created = Account.objects.select_for_update().get_or_create(account_number=fee_account_number, defaults={'balance': transaction_fee})
(Pdb) is_created
True
(Pdb) fee_account
<Account:  | 1>
(Pdb) fee_account.account_number
''
(Pdb) fee_account_number
(Pdb) print(fee_account_number)
None
```

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/79
