### ISSUE TITLE
URL naming convention

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#76]
Should we rename [this endpoint](https://github.com/thenewboston-developers/Core/blob/master/core/settings/urls.py#L6) from `/config` to `/settings` since it is not part of the `config` app but rather the `settings` app?

**Comment by buckyroberts** [comment]
From meeting:
- `config > project`
- `settings > config`

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/81

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/82
