### ISSUE TITLE
Updated balances streamed to recipient

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#8]
Recipient should receive any updated balance in WS payload along with incoming message. This will prevent them from needing to make an additional request.

TODO:
- [DONE] Change WS URL: https://github.com/thenewboston-developers/Core/issues/84
- [DONE] Implement message typing
- [DONE] Introduce apply on commit
- Add balance type (actually, we stream an account change)

**Comment by dmugtasimov** [comment]
@buckyroberts now it gets only balance increase or message with amount 0 notification. Do you mean that we should also include balance decrease notifications? What about POST messages with amount 0 that are send via POST request. Should we notify sender about these messages as well.

In all cases notification is a copy of the block?

**Comment by buckyroberts** [comment]
Note from meeting - we decided that any/all updated balances will be streamed down to those users.

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/issues/84 to be implemented here

**Comment by dmugtasimov** [comment]
@buckyroberts we also decided that the balance update is delivered with its own message type

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/85

**Comment by dmugtasimov** [comment]
@buckyroberts please, be aware of WS message format change: https://github.com/thenewboston-developers/Core/pull/87

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/88

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/90
