### ISSUE TITLE
Prohibit block update on model level

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/Core#89]
```
        if not self._state.adding:
            # TODO(dmu) CRITICAL: Prohibit block update
            #                     https://github.com/thenewboston-developers/Core/issues/89
            logger.warning('Block update is not allowed')
```

**Comment by dmugtasimov** [comment]
@buckyroberts please, let me know if I should work on this task

**Comment by buckyroberts** [comment]
@dmugtasimov yes, please work on this task.

**Comment by dmugtasimov** [comment]
@buckyroberts After some considerations I decided to postpone this task. Here are the reasons:
1. We already have update prohibition on API level: PATCH and PUT for blocks are not allowed and we have unittest for it.
2. Django Admin does not have an easy way of disabling editing. We should probably remove "SAVE" button from form template. Also it is unclear if we should really disable editing in Django Admin since usually superuser has all right even if this may lead to data inconsistency. Assuming that superusers know what they are doing.
3. If we decide to disable update in Django Admin then to be consistent we should disable deletion as well. The latter would make debugging / testing harder. Since now for integration testing I just delete the existing block and reuse API request to create it again (this allows not to sign the request each time, since the same block is sent).
