### ISSUE TITLE
Add account_number to update.account

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#93]
Include `account_number` in the `update.account` WS message. This is because the client will have multiple WS connections open and this will make it easier to track which account the updates are for.

```json
{
    "type": "update.account",
    "message": {
        "account_number": "995bd2a4db610062f404510617e83126fa37e28365523634c805975f334108b5" # this
        "balance": 25
    }
}
```

**Comment by dmugtasimov** [comment]
https://github.com/thenewboston-developers/Core/pull/94
