### ISSUE TITLE
Remove avatar and display_name

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#97]
Remove `avatar` and `display_name` from `Account` model.

**Comment by dmugtasimov** [comment]
Django upgraded: https://github.com/thenewboston-developers/Core/pull/101

**Comment by dmugtasimov** [comment]
READMEs brush up: https://github.com/thenewboston-developers/Core/pull/102

**Comment by dmugtasimov** [comment]
Done here: https://github.com/thenewboston-developers/Core/pull/103
