### ISSUE TITLE
Deployment guide(s)

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#98]
Create a detailed deployment guide on how to deploy the Core server on AWS. I will follow this guide in a tutorial and will share the guide with the viewers as well. Please also include detailed instructions on setting up a domain name and HTTPS/SSL.

**Comment by dmugtasimov** [comment]
DRYer code: https://github.com/thenewboston-developers/Core/pull/104

**Comment by dmugtasimov** [comment]
There is a long standing issue with github not allowing to pull images without authentication: https://github.community/t/download-from-github-package-registry-without-authentication/14407

Some people suggest a workaround of pregenerating a PAT with limited access and publish it (we could hardcode it in a deploy script). But I am not sure how much secure this work around is. Will have to research.

**Comment by dmugtasimov** [comment]
@buckyroberts I parametrized email and domain name. With multiple PRs, so not posting them here. Please, take a look. As for github authenticated only docker pull, I will review it a little bit later.

**Comment by dmugtasimov** [comment]
@buckyroberts I added detailed steps of how to get PAT on github: https://github.com/thenewboston-developers/Core/pull/113

Further options may be:

1. Create fake (special purpose) github user and generate PAT for it and then hard code (meaning publish as well) the PAT in our deploy scripts, so authentication is never asked explicitly (or we can even leave it as an option providing user's own PAT)
2. Publish docker images to Docker Hub registry. It may require storing Docker Hub user password in github secrets
3. Publish docker images to AWS ECR. This looks fine by accepting AWS access tokens (not passwords)
4. Explore other registries like gitlab, etc.

Please, let me know if I should explore any of these options or it is good enough to just have PAT acquisition steps described.
