### ISSUE TITLE
Client library

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Core#99]
Create a client library (in a separate repo) to make it easier for developers to interact with their Core servers. I will be teaching developers how to deploy their own Core servers as part of a tutorial series so the library will need to allow for a configurable URL (rather than hardcoding in https://thenewboston.network/). It will also be used when developing on localhost so we will need to allow for custom protocol and port number as well.

**Functionality**
- create new account (signing key/account number keypair) where they must specify a file path where the signing key will be saved
- load in existing account from signing key file
- connect to core server by inputting domain, protocol, and port
- send signed messages/blocks to the core
- verify signature/signed messages

Here is the old repo from the blockchain project https://github.com/thenewboston-blockchain/thenewboston-python Much of the functionality can likely just be copied over.

Please also provide documentation and configure CI/CD to publish to PyPI on pushes to `master`.

**Comment by dmugtasimov** [comment]
@buckyroberts having it as a library is fine and I can do it, but what do you think about providing docker image? also we can provide a library published on PyPI and a docker image that depends on that library

**Comment by buckyroberts** [comment]
@buckyroberts add in WS requirements to support stateful services
